default_install_hook_types: [pre-commit, pre-push]
exclude: "^original/"
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.3
    hooks:
      - id: clang-format
        types_or: [c++, c]
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        language: system
        types: [rust]
        entry: bash -c 'cd others/rust && cargo fmt'
        pass_filenames: false
      - id: clippy
        name: clippy
        language: system
        types: [rust]
        entry:
          bash -c 'cd others/rust && cargo clippy --all-targets --all-features
          -- -D warnings -W clippy::all -W clippy::cargo -W clippy::complexity
          -W clippy::correctness -W clippy::pedantic -W clippy::perf -W
          clippy::style -W clippy::suspicious'
        pass_filenames: false
      - id: doc
        name: doc
        language: system
        types: [rust]
        entry: bash -c 'cd others/rust && cargo doc --no-deps --all-features'
        pass_filenames: false
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/PyCQA/docformatter
    rev: eb1df347edd128b30cd3368dddc3aa65edcfac38
    hooks:
      - id: docformatter
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.394
    hooks:
      - id: pyright
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.5.1
    hooks:
      - id: prettier
