[package]
name = "moontool"
version = "1.4.0"
edition = "2024"
authors = ["Quentin Richert <noreply@richert.co>"]
description = "John Walker's moontool.c astronomical calculation routines, extracted and ported to Rust."
license = "0BSD"
repository = "https://github.com/qrichert/moontool.git"
keywords = ["moon-phase", "lunar", "lunation", "astronomy", "moon-calendar"]
categories = ["aerospace", "mathematics", "science", "date-and-time", "command-line-utilities"]

[[bin]]
name = "moontool"
required-features = ["rich-output"]

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)', 'cfg(PARANOID)'] }

[dependencies]
# (CLI) Render Moon and plot lunation charts.
textcanvas = { version = "3.9.0", optional = true }
# Manipulate dates and time.
# - Get current date and time.
# - Convert from-and-to timestamps.
# - Parse ISO datetime strings.
# - Get day-of-week for date.
# - Convert between local and UTC.
jiff = "0.2.35"

[features]
# (CLI) Activate `textcanvas` dependency for rich output.
rich-output = ["dep:textcanvas"]
