[package]
name = "moontool"
version = "0.3.1"
edition = "2021"
authors = ["Quentin Richert <noreply@richert.co>"]
description = "John Walker's moontool.c astronomical calculation routines, extracted and ported to Rust."
license = "0BSD"
repository = "https://github.com/qrichert/moontool.git"
readme = "../../README.md"
keywords = ["moon"]
categories = ["aerospace", "mathematics", "science", "command-line-utilities"]

[profile.release]
strip = true

[dependencies]
time = { version = "0.3", features = ["std", "parsing", "local-offset"] }
textcanvas = { version = "2.1", optional = true }

[features]
canvas = ["textcanvas"]

[[bin]]
name = "moontool"
required-features = ["canvas"]
