/*
        Set Universal Time dialogue item definitions
*/

#define IDC_U_YEAR                  6001
#define IDC_U_MONTH                 6003
#define IDC_U_DAY                   6004
#define IDC_U_HOUR                  6005
#define IDC_U_MINUTE                6006
#define IDC_U_SECOND                6007
#define IDC_U_NOW                   6015
#define IDC_U_JDATE                 6016
