//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Moontool.rc
//
#define IDS_ERR_REGISTER_CLASS          1
#define IDS_ERR_CREATE_WINDOW           2
#define IDS_ERR_TRUEPHASE               3
#define IDS_ERR_IERR                    4
#define IDS_ITEM_LABELS                 16
#define IDS_ITEM_LABELS_N               18
#define IDS_MONTH_NAMES                 48
#define IDS_FORMATS                     64
#define IDS_MINUTE                      96
#define IDS_MINUTES                     97
#define IDS_HOUR                        98
#define IDS_HOURS                       99
#define IDD_ABOUT                       100
#define IDM_ABOUT                       100
#define IDS_DAY                         100
#define IDS_DAYS                        101
#define IDS_APPNAME                     102
#define MOONTOOL_ICON                   102
#define IDR_POPUP                       103
#define IDS_HELPFILE                    103
#define IDM_FILE                        1000
#define IDM_F_EXIT                      1050
#define IDM_EDIT                        2000
#define IDM_F_COPY                      2050
#define IDM_OPTIONS                     3000
#define IDM_F_TESTMODE                  3050
#define IDM_F_STOP                      3060
#define IDM_F_RUN                       3070
#define IDM_F_SETJDATE                  3080
#define IDM_F_SETUTIME                  3090
#define IDM_HELP                        4000
#define IDM_F_ABOUT                     4050
#define IDM_F_TIMEZONE                  4060
#define IDD_TIMEZONE                    5000
#define IDM_TIMEZONE                    5000
#define IDD_SET_UTC                     6000
#define IDC_U_YEAR                      6001
#define IDC_U_MONTH                     6003
#define IDC_U_DAY                       6004
#define IDC_U_HOUR                      6005
#define IDC_U_MINUTE                    6006
#define IDC_U_SECOND                    6007
#define IDC_U_NOW                       6015
#define IDC_U_JDATE                     6016
#define IDD_SET_JULIAN                  9000
#define IDC_J_UTIME                     9001
#define IDC_J_NOW                       9003
#define IDC_J_JDATE                     9005
#define ID_POPUP_OPEN                   40001
#define ID_POPUP_EXIT                   40002
#define IDM_HELP_CONTENTS               40004
#define IDM_HELP_SEARCH                 40005
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40006
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
