SOURCE_DIRS := "moontool tests"

@_default:
    just --list --list-prefix '  '

# Clean project files
clean:
    rm -rf ./var/htmlcov
    rm -rf ./.coverage
    rm -rf ./.ruff_cache/
    rm -rf ./__pycache__/
    find {{ SOURCE_DIRS }} -name "__pycache__" -prune -exec rm -rf {} \;
    find {{ SOURCE_DIRS }} -name "*.py[co]" -prune -exec rm -rf {} \;
    find {{ SOURCE_DIRS }} -name "*.so" -prune -exec rm -rf {} \;

alias r := run
# Build and run program
run:
    python -m moontool

# Most stringent checks (includes checks still in development)
check:
    prek run ruff --all-files
    prek run ruff-format --all-files
    prek run docformatter --all-files
    prek run pyright --all-files
    just test

alias t := test
# Run unit tests
test:
    python -m unittest

alias c := coverage
# Unit tests coverage report
coverage:
    rm -rf var/htmlcov
    python -m coverage run -m unittest
    python -m coverage html -d var/htmlcov
    # python -m coverage report
    open var/htmlcov/index.html || xdg-open var/htmlcov/index.html || :

# Ensure code coverage of at least 99%
coverage-pct:
    python -m coverage run -m unittest > /dev/null 2>&1 || :
    python -m coverage json -q -o /dev/stdout | python -c 'import decimal, json, sys; coverage = json.loads(input(), parse_float=decimal.Decimal); percent_covered = coverage["totals"]["percent_covered"]; print(percent_covered); sys.exit(0 if percent_covered >= 99 else 1);'
