name: CI

on:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - 'others/rust/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'others/rust/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [lint, test, coverage-pct, doc]
    defaults:
      run:
        working-directory: ./others/rust

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Just
        uses: taiki-e/install-action@just

      - name: Cache cargo registry and build
        if: matrix.target != 'coverage-pct'
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/
            ~/.cargo/git/
            target/
          key:
            ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.target }}-
            ${{ runner.os }}-cargo-

      - name: Install Tarpaulin
        if: matrix.target == 'coverage-pct'
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-tarpaulin

      - name: Cache prek
        if: matrix.target == 'lint'
        uses: actions/cache@v4
        with:
          path: ~/.cache/prek/
          key:
            ${{ runner.os }}-prek-${{ hashFiles('**/.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-prek-

      - name: Install prek
        if: matrix.target == 'lint'
        uses: taiki-e/install-action@v2
        with:
          tool: prek

      - name: Run Justfile target
        run: just ${{ matrix.target }}
